// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjZK5ojHcJQh8Sr0sdMG0Nlnga4D94FME',
    appId: '1:915941234935:web:0a0e401e56ec1267311bf2',
    messagingSenderId: '915941234935',
    projectId: 'searchaholic-86248',
    authDomain: 'searchaholic-86248.firebaseapp.com',
    storageBucket: 'searchaholic-86248.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeAuqTXFXec3UHa6NFLC9GHaD4IK7RXUg',
    appId: '1:915941234935:android:c7784fa6132f97b4311bf2',
    messagingSenderId: '915941234935',
    projectId: 'searchaholic-86248',
    storageBucket: 'searchaholic-86248.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR1-V5DqjCEZnFDy7FWCjurBIxv1SVnfY',
    appId: '1:915941234935:ios:25c73818b795f2bd311bf2',
    messagingSenderId: '915941234935',
    projectId: 'searchaholic-86248',
    storageBucket: 'searchaholic-86248.appspot.com',
    iosClientId: '915941234935-c033rr81l528f6onaok7j3paneqomttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.searchaholic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR1-V5DqjCEZnFDy7FWCjurBIxv1SVnfY',
    appId: '1:915941234935:ios:25c73818b795f2bd311bf2',
    messagingSenderId: '915941234935',
    projectId: 'searchaholic-86248',
    storageBucket: 'searchaholic-86248.appspot.com',
    iosClientId: '915941234935-c033rr81l528f6onaok7j3paneqomttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.searchaholic',
  );
}
